-- Drop existing tables if they exist (to handle fresh import)
DROP TABLE IF EXISTS `barangays`;
DROP TABLE IF EXISTS `cities`;
DROP TABLE IF EXISTS `provinces`;

-- Create Philippine Provinces Table
CREATE TABLE `provinces` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `province_code` varchar(50) NOT NULL,
  `province_name` varchar(100) NOT NULL,
  `region_code` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `province_code` (`province_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Philippine Cities/Municipalities Table
CREATE TABLE `cities` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `city_code` varchar(10) NOT NULL,
  `city_name` varchar(100) NOT NULL,
  `province_code` varchar(50) NOT NULL,
  `city_type` enum('City','Municipality') DEFAULT 'Municipality',
  PRIMARY KEY (`id`),
  UNIQUE KEY `city_code` (`city_code`),
  KEY `province_code` (`province_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Philippine Barangays Table
CREATE TABLE `barangays` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `barangay_code` varchar(10) NOT NULL,
  `barangay_name` varchar(100) NOT NULL,
  `city_code` varchar(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `barangay_code` (`barangay_code`),
  KEY `city_code` (`city_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert Major Philippine Provinces (Sample data - can be expanded)
INSERT INTO `provinces` (`province_code`, `province_name`, `region_code`) VALUES
('ABRA', 'Abra', 'CAR'),
('AGUSAN DEL NORTE', 'Agusan del Norte', 'CARAGA'),
('AKLAN', 'Aklan', 'VI'),
('ALBAY', 'Albay', 'V'),
('ANTIQUE', 'Antique', 'VI'),
('APAYAO', 'Apayao', 'CAR'),
('AURORA', 'Aurora', 'III'),
('BASILAN', 'Basilan', 'BARMM'),
('BATAAN', 'Bataan', 'III'),
('BATANES', 'Batanes', 'II'),
('BATANGAS', 'Batangas', 'IV-A'),
('BENGUET', 'Benguet', 'CAR'),
('BILIRAN', 'Biliran', 'VIII'),
('BOHOL', 'Bohol', 'VII'),
('BUKIDNON', 'Bukidnon', 'X'),
('BULACAN', 'Bulacan', 'III'),
('CAGAYAN', 'Cagayan', 'II'),
('CAMARINES SUR', 'Camarines Sur', 'V'),
('CAMIGUIN', 'Camiguin', 'X'),
('CAPIZ', 'Capiz', 'VI'),
('CATANDUANES', 'Catanduanes', 'V'),
('CAVITE', 'Cavite', 'IV-A'),
('CEBU', 'Cebu', 'VII'),
('COMPOSTELA VALLEY', 'Compostela Valley', 'XI'),
('COTABATO', 'Cotabato (North)', 'XII'),
('DAVAO DEL NORTE', 'Davao del Norte', 'XI'),
('DAVAO DEL SUR', 'Davao del Sur', 'XI'),
('DAVAO OCCIDENTAL', 'Davao Occidental', 'XI'),
('DAVAO ORIENTAL', 'Davao Oriental', 'XI'),
('DINAGAT ISLANDS', 'Dinagat Islands', 'CARAGA'),
('EASTERN SAMAR', 'Eastern Samar', 'VIII'),
('GUIMARAS', 'Guimaras', 'VI'),
('IFUGAO', 'Ifugao', 'CAR'),
('ILOCOS NORTE', 'Ilocos Norte', 'I'),
('ILOCOS SUR', 'Ilocos Sur', 'I'),
('ILOILO', 'Iloilo', 'VI'),
('ISABELA', 'Isabela', 'II'),
('KALINGA', 'Kalinga', 'CAR'),
('LA UNION', 'La Union', 'I'),
('LAGUNA', 'Laguna', 'IV-A'),
('LANAO DEL NORTE', 'Lanao del Norte', 'BARMM'),
('LANAO DEL SUR', 'Lanao del Sur', 'BARMM'),
('LEYTE', 'Leyte', 'VIII'),
('MAGUINDANAO', 'Maguindanao', 'BARMM'),
('MARINDUQUE', 'Marinduque', 'IV-B'),
('MASBATE', 'Masbate', 'V'),
('METRO MANILA', 'Metro Manila', 'NCR'),
('MISAMIS OCCIDENTAL', 'Misamis Occidental', 'X'),
('MISAMIS ORIENTAL', 'Misamis Oriental', 'X'),
('MOUNTAIN PROVINCE', 'Mountain Province', 'CAR'),
('NEGROS OCCIDENTAL', 'Negros Occidental', 'VI'),
('NEGROS ORIENTAL', 'Negros Oriental', 'VII'),
('NORTH COTABATO', 'North Cotabato', 'XII'),
('NORTHERN SAMAR', 'Northern Samar', 'VIII'),
('NUEVA ECIJA', 'Nueva Ecija', 'III'),
('NUEVA VIZCAYA', 'Nueva Vizcaya', 'II'),
('OCCIDENTAL MINDORO', 'Occidental Mindoro', 'IV-B'),
('ORIENTAL MINDORO', 'Oriental Mindoro', 'IV-B'),
('PALAWAN', 'Palawan', 'IV-B'),
('PAMPANGA', 'Pampanga', 'III'),
('PANGASINAN', 'Pangasinan', 'I'),
('QUEZON', 'Quezon', 'IV-A'),
('QUIRINO', 'Quirino', 'II'),
('RIZAL', 'Rizal', 'IV-A'),
('ROMBLON', 'Romblon', 'IV-B'),
('SARANGANI', 'Sarangani', 'XII'),
('SIQUIJOR', 'Siquijor', 'VII'),
('SORSOGON', 'Sorsogon', 'V'),
('SOUTH COTABATO', 'South Cotabato', 'XII'),
('SOUTHERN LEYTE', 'Southern Leyte', 'VIII'),
('SULTAN KUDARAT', 'Sultan Kudarat', 'XII'),
('SULU', 'Sulu', 'BARMM'),
('SURIGAO DEL NORTE', 'Surigao del Norte', 'CARAGA'),
('SURIGAO DEL SUR', 'Surigao del Sur', 'CARAGA'),
('TARLAC', 'Tarlac', 'III'),
('TAWI-TAWI', 'Tawi-Tawi', 'BARMM'),
('ZAMBALES', 'Zambales', 'III'),
('ZAMBOANGA DEL NORTE', 'Zamboanga del Norte', 'IX'),
('ZAMBOANGA DEL SUR', 'Zamboanga del Sur', 'IX'),
('ZAMBOANGA SIBUGAY', 'Zamboanga Sibugay', 'IX'),
('ZAMBOANGA CITY', 'Zamboanga City (Highly Urbanized)', 'IX');

-- Insert Sample Cities/Municipalities for Major Provinces
INSERT INTO `cities` (`city_code`, `city_name`, `province_code`, `city_type`) VALUES
-- Metro Manila
('MM001', 'Manila', 'METRO MANILA', 'City'),
('MM002', 'Quezon City', 'METRO MANILA', 'City'),
('MM003', 'Caloocan', 'METRO MANILA', 'City'),
('MM004', 'Las Piñas', 'METRO MANILA', 'City'),
('MM005', 'Makati', 'METRO MANILA', 'City'),
('MM006', 'Malabon', 'METRO MANILA', 'City'),
('MM007', 'Mandaluyong', 'METRO MANILA', 'City'),
('MM008', 'Marikina', 'METRO MANILA', 'City'),
('MM009', 'Muntinlupa', 'METRO MANILA', 'City'),
('MM010', 'Navotas', 'METRO MANILA', 'City'),
('MM011', 'Parañaque', 'METRO MANILA', 'City'),
('MM012', 'Pasay', 'METRO MANILA', 'City'),
('MM013', 'Pasig', 'METRO MANILA', 'City'),
('MM014', 'Pateros', 'METRO MANILA', 'Municipality'),
('MM015', 'San Juan', 'METRO MANILA', 'City'),
('MM016', 'Taguig', 'METRO MANILA', 'City'),
('MM017', 'Valenzuela', 'METRO MANILA', 'City'),
-- Cebu
('CEB001', 'Cebu City', 'CEBU', 'City'),
('CEB002', 'Mandaue', 'CEBU', 'City'),
('CEB003', 'Lapu-Lapu', 'CEBU', 'City'),
('CEB004', 'Talisay', 'CEBU', 'City'),
('CEB005', 'Naga', 'CEBU', 'City'),
('CEB006', 'Carcar', 'CEBU', 'City'),
('CEB007', 'Danao', 'CEBU', 'City'),
('CEB008', 'Toledo', 'CEBU', 'City'),
('CEB009', 'Bogo', 'CEBU', 'City'),
('CEB010', 'Argao', 'CEBU', 'Municipality'),
('CEB011', 'Barili', 'CEBU', 'Municipality'),
('CEB012', 'Badian', 'CEBU', 'Municipality'),
('CEB013', 'Balamban', 'CEBU', 'Municipality'),
('CEB014', 'Bantayan', 'CEBU', 'Municipality'),
('CEB015', 'Barili', 'CEBU', 'Municipality'),
-- Davao del Sur
('DAVS001', 'Davao City', 'DAVAO DEL SUR', 'City'),
('DAVS002', 'Digos', 'DAVAO DEL SUR', 'City'),
('DAVS003', 'Davao City', 'DAVAO DEL SUR', 'City'),
('DAVS004', 'Bansalan', 'DAVAO DEL SUR', 'Municipality'),
('DAVS005', 'Hagonoy', 'DAVAO DEL SUR', 'Municipality'),
('DAVS006', 'Kapatagan', 'DAVAO DEL SUR', 'Municipality'),
('DAVS007', 'Magsaysay', 'DAVAO DEL SUR', 'Municipality'),
('DAVS008', 'Malalag', 'DAVAO DEL SUR', 'Municipality'),
('DAVS009', 'Matanao', 'DAVAO DEL SUR', 'Municipality'),
('DAVS010', 'Padada', 'DAVAO DEL SUR', 'Municipality'),
-- Cavite
('CAV001', 'Bacoor', 'CAVITE', 'City'),
('CAV002', 'Cavite City', 'CAVITE', 'City'),
('CAV003', 'Dasmariñas', 'CAVITE', 'City'),
('CAV004', 'Imus', 'CAVITE', 'City'),
('CAV005', 'Tagaytay', 'CAVITE', 'City'),
('CAV006', 'Trece Martires', 'CAVITE', 'City'),
('CAV007', 'General Trias', 'CAVITE', 'City'),
('CAV008', 'Tanza', 'CAVITE', 'City'),
('CAV009', 'Alfonso', 'CAVITE', 'Municipality'),
('CAV010', 'Amadeo', 'CAVITE', 'Municipality'),
('CAV011', 'Carmona', 'CAVITE', 'Municipality'),
('CAV012', 'Gen. Mariano Alvarez', 'CAVITE', 'Municipality'),
('CAV013', 'Indang', 'CAVITE', 'Municipality'),
('CAV014', 'Kawit', 'CAVITE', 'Municipality'),
('CAV015', 'Magallanes', 'CAVITE', 'Municipality'),
('CAV016', 'Maragondon', 'CAVITE', 'Municipality'),
('CAV017', 'Mendez', 'CAVITE', 'Municipality'),
('CAV018', 'Naic', 'CAVITE', 'Municipality'),
('CAV019', 'Noveleta', 'CAVITE', 'Municipality'),
('CAV020', 'Rosario', 'CAVITE', 'Municipality'),
('CAV021', 'Silang', 'CAVITE', 'Municipality'),
('CAV022', 'Ternate', 'CAVITE', 'Municipality');

-- Insert Sample Barangays for Sample Cities
INSERT INTO `barangays` (`barangay_code`, `barangay_name`, `city_code`) VALUES
-- Manila
('MM001001', 'Binondo', 'MM001'),
('MM001002', 'Ermita', 'MM001'),
('MM001003', 'Intramuros', 'MM001'),
('MM001004', 'Malate', 'MM001'),
('MM001005', 'Paco', 'MM001'),
('MM001006', 'Pandacan', 'MM001'),
('MM001007', 'Port Area', 'MM001'),
('MM001008', 'Quiapo', 'MM001'),
('MM001009', 'Sampaloc', 'MM001'),
('MM001010', 'San Andres', 'MM001'),
('MM001011', 'San Miguel', 'MM001'),
('MM001012', 'San Nicolas', 'MM001'),
('MM001013', 'Santa Ana', 'MM001'),
('MM001014', 'Santa Cruz', 'MM001'),
('MM001015', 'Santa Mesa', 'MM001'),
('MM001016', 'Tondo', 'MM001'),
-- Quezon City
('MM002001', 'Bago Bantay', 'MM002'),
('MM002002', 'Bagumbayan', 'MM002'),
('MM002003', 'Bahay Toro', 'MM002'),
('MM002004', 'Balingasa', 'MM002'),
('MM002005', 'Balong Bato', 'MM002'),
('MM002006', 'Barangka', 'MM002'),
('MM002007', 'Batasan Hills', 'MM002'),
('MM002008', 'Batasan Hills', 'MM002'),
('MM002009', 'Commonwealth', 'MM002'),
('MM002010', 'Diliman', 'MM002'),
('MM002011', 'Fairview', 'MM002'),
('MM002012', 'Gulod', 'MM002'),
('MM002013', 'Holy Spirit', 'MM002'),
('MM002014', 'Kaligayahan', 'MM002'),
('MM002015', 'Kamuning', 'MM002'),
-- Cebu City
('CEB001001', 'Adlaon', 'CEB001'),
('CEB001002', 'Agsungot', 'CEB001'),
('CEB001003', 'Apas', 'CEB001'),
('CEB001004', 'Babag', 'CEB001'),
('CEB001005', 'Bacayan', 'CEB001'),
('CEB001006', 'Banilad', 'CEB001'),
('CEB001007', 'Binaliw', 'CEB001'),
('CEB001008', 'Budlaan', 'CEB001'),
('CEB001009', 'Busay', 'CEB001'),
('CEB001010', 'Calamba', 'CEB001'),
('CEB001011', 'Capitol Site', 'CEB001'),
('CEB001012', 'Carreta', 'CEB001'),
('CEB001013', 'Cebu City', 'CEB001'),
('CEB001014', 'Cogon', 'CEB001'),
('CEB001015', 'Compostela', 'CEB001'),
-- Davao City
('DAVS001001', 'Agdao', 'DAVS001'),
('DAVS001002', 'Bago Oshiro', 'DAVS001'),
('DAVS001003', 'Buhangin', 'DAVS001'),
('DAVS001004', 'Bunawan', 'DAVS001'),
('DAVS001005', 'Catalunan Grande', 'DAVS001'),
('DAVS001006', 'Catalunan Pequeño', 'DAVS001'),
('DAVS001007', 'Cawa-Cawa', 'DAVS001'),
('DAVS001008', 'Daliao', 'DAVS001'),
('DAVS001009', 'Talomo', 'DAVS001'),
('DAVS001010', 'Tugbok', 'DAVS001'),
('DAVS001011', 'Toril', 'DAVS001'),
('DAVS001012', 'Poblacion', 'DAVS001'),
('DAVS001013', 'Bucana', 'DAVS001'),
('DAVS001014', 'Lanang', 'DAVS001'),
('DAVS001015', 'Sasa', 'DAVS001'),
-- Bacoor
('CAV001001', 'Aniban', 'CAV001'),
('CAV001002', 'Banalo', 'CAV001'),
('CAV001003', 'Bayanan', 'CAV001'),
('CAV001004', 'Cabuco', 'CAV001'),
('CAV001005', 'Casimiro', 'CAV001'),
('CAV001006', 'Dulong Bayan', 'CAV001'),
('CAV001007', 'Habay', 'CAV001'),
('CAV001008', 'Kaingin', 'CAV001'),
('CAV001009', 'Mababa', 'CAV001'),
('CAV001010', 'Molino', 'CAV001'),
('CAV001011', 'Niog', 'CAV001'),
('CAV001012', 'Poblacion', 'CAV001'),
('CAV001013', 'Real', 'CAV001'),
('CAV001014', 'San Nicolas', 'CAV001'),
('CAV001015', 'Sineguelasan', 'CAV001'),
('CAV001016', 'Tabing Dagat', 'CAV001'),
('CAV001017', 'Talaba', 'CAV001'),
('CAV001018', 'Talon', 'CAV001'),
('CAV001019', 'Tirona', 'CAV001'),
('CAV001020', 'Zapote', 'CAV001');
