-- Drop existing settings_address table if it exists
DROP TABLE IF EXISTS `settings_address`;

-- Create settings_address table with hierarchical structure
CREATE TABLE `settings_address` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `province` varchar(100) NOT NULL,
  `city_mun` varchar(100) NOT NULL,
  `barangay` varchar(100) NOT NULL,
  `region` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `province` (`province`),
  KEY `city_mun` (`city_mun`),
  KEY `barangay` (`barangay`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert Philippine provinces, cities, and barangays
-- Metro Manila
INSERT INTO `settings_address` (`province`, `city_mun`, `barangay`, `region`) VALUES
('Metro Manila', 'Manila', 'Binondo', 'NCR'),
('Metro Manila', 'Manila', 'Ermita', 'NCR'),
('Metro Manila', 'Manila', 'Intramuros', 'NCR'),
('Metro Manila', 'Manila', 'Malate', 'NCR'),
('Metro Manila', 'Manila', 'Paco', 'NCR'),
('Metro Manila', 'Manila', 'Pandacan', 'NCR'),
('Metro Manila', 'Manila', 'Port Area', 'NCR'),
('Metro Manila', 'Manila', 'Quiapo', 'NCR'),
('Metro Manila', 'Manila', 'Sampaloc', 'NCR'),
('Metro Manila', 'Manila', 'San Andres', 'NCR'),
('Metro Manila', 'Manila', 'San Miguel', 'NCR'),
('Metro Manila', 'Manila', 'San Nicolas', 'NCR'),
('Metro Manila', 'Manila', 'Santa Ana', 'NCR'),
('Metro Manila', 'Manila', 'Santa Cruz', 'NCR'),
('Metro Manila', 'Manila', 'Santa Mesa', 'NCR'),
('Metro Manila', 'Manila', 'Tondo', 'NCR'),
('Metro Manila', 'Quezon City', 'Bago Bantay', 'NCR'),
('Metro Manila', 'Quezon City', 'Bagumbayan', 'NCR'),
('Metro Manila', 'Quezon City', 'Bahay Toro', 'NCR'),
('Metro Manila', 'Quezon City', 'Balingasa', 'NCR'),
('Metro Manila', 'Quezon City', 'Balong Bato', 'NCR'),
('Metro Manila', 'Quezon City', 'Barangka', 'NCR'),
('Metro Manila', 'Quezon City', 'Batasan Hills', 'NCR'),
('Metro Manila', 'Quezon City', 'Commonwealth', 'NCR'),
('Metro Manila', 'Quezon City', 'Diliman', 'NCR'),
('Metro Manila', 'Quezon City', 'Fairview', 'NCR'),
('Metro Manila', 'Quezon City', 'Gulod', 'NCR'),
('Metro Manila', 'Quezon City', 'Holy Spirit', 'NCR'),
('Metro Manila', 'Quezon City', 'Kaligayahan', 'NCR'),
('Metro Manila', 'Quezon City', 'Kamuning', 'NCR'),
('Metro Manila', 'Caloocan', 'Bagumbong', 'NCR'),
('Metro Manila', 'Caloocan', 'Bagong Silang', 'NCR'),
('Metro Manila', 'Caloocan', 'Barangay 176', 'NCR'),
('Metro Manila', 'Caloocan', 'Kaybiga', 'NCR'),
('Metro Manila', 'Caloocan', 'Ligas', 'NCR'),
('Metro Manila', 'Las Piñas', 'Almanza', 'NCR'),
('Metro Manila', 'Las Piñas', 'Daniel Fajardo', 'NCR'),
('Metro Manila', 'Las Piñas', 'Elias Aldana', 'NCR'),
('Metro Manila', 'Las Piñas', 'Manuyo Uno', 'NCR'),
('Metro Manila', 'Makati', 'Bel-Air', 'NCR'),
('Metro Manila', 'Makati', 'Belen', 'NCR'),
('Metro Manila', 'Makati', 'Carmona', 'NCR'),
('Metro Manila', 'Makati', 'Dasmariñas', 'NCR'),
('Metro Manila', 'Makati', 'Guadalupe Viejo', 'NCR'),
('Metro Manila', 'Makati', 'Pembo', 'NCR'),
('Metro Manila', 'Malabon', 'Agus', 'NCR'),
('Metro Manila', 'Malabon', 'Baritan', 'NCR'),
('Metro Manila', 'Malabon', 'Dampalit', 'NCR'),
('Metro Manila', 'Malabon', 'Florentino', 'NCR'),
('Metro Manila', 'Mandaluyong', 'Addition Hills', 'NCR'),
('Metro Manila', 'Mandaluyong', 'Bagong Silang', 'NCR'),
('Metro Manila', 'Mandaluyong', 'Buayang Bato', 'NCR'),
('Metro Manila', 'Mandaluyong', 'Hulo', 'NCR'),
('Metro Manila', 'Marikina', 'Barangka', 'NCR'),
('Metro Manila', 'Marikina', 'Concepcion', 'NCR'),
('Metro Manila', 'Marikina', 'Jesus de la Peña', 'NCR'),
('Metro Manila', 'Marikina', 'Malanday', 'NCR'),
('Metro Manila', 'Muntinlupa', 'Alabang', 'NCR'),
('Metro Manila', 'Muntinlupa', 'Ayala Alabang', 'NCR'),
('Metro Manila', 'Muntinlupa', 'Bayanan', 'NCR'),
('Metro Manila', 'Muntinlupa', 'Buli', 'NCR'),
('Metro Manila', 'Navotas', 'Bagumbayan North', 'NCR'),
('Metro Manila', 'Navotas', 'Bagumbayan South', 'NCR'),
('Metro Manila', 'Navotas', 'Bangkulasi', 'NCR'),
('Metro Manila', 'Navotas', 'Navotas East', 'NCR'),
('Metro Manila', 'Parañaque', 'Baclaran', 'NCR'),
('Metro Manila', 'Parañaque', 'BF Homes', 'NCR'),
('Metro Manila', 'Parañaque', 'Don Galo', 'NCR'),
('Metro Manila', 'Parañaque', 'La Huerta', 'NCR'),
('Metro Manila', 'Pasay', 'Barangay 1', 'NCR'),
('Metro Manila', 'Pasay', 'Barangay 2', 'NCR'),
('Metro Manila', 'Pasay', 'Barangay 3', 'NCR'),
('Metro Manila', 'Pasay', 'Barangay 4', 'NCR'),
('Metro Manila', 'Pasig', 'Bagong Ilog', 'NCR'),
('Metro Manila', 'Pasig', 'Buting', 'NCR'),
('Metro Manila', 'Pasig', 'Caniogan', 'NCR'),
('Metro Manila', 'Pasig', 'Kapitolyo', 'NCR'),
('Metro Manila', 'Pateros', 'Aguho', 'NCR'),
('Metro Manila', 'Pateros', 'Kalawaan', 'NCR'),
('Metro Manila', 'Pateros', 'Martires', 'NCR'),
('Metro Manila', 'San Juan', 'Addition Hills', 'NCR'),
('Metro Manila', 'San Juan', 'Balong Bato', 'NCR'),
('Metro Manila', 'San Juan', 'Bayan', 'NCR'),
('Metro Manila', 'San Juan', 'Corazon de Jesus', 'NCR'),
('Metro Manila', 'Taguig', 'Bambang', 'NCR'),
('Metro Manila', 'Taguig', 'Hagonoy', 'NCR'),
('Metro Manila', 'Taguig', 'Ligid Tipas', 'NCR'),
('Metro Manila', 'Taguig', 'Lower Bicutan', 'NCR'),
('Metro Manila', 'Valenzuela', 'Canumay', 'NCR'),
('Metro Manila', 'Valenzuela', 'Dalandanan', 'NCR'),
('Metro Manila', 'Valenzuela', 'Malanday', 'NCR'),
('Metro Manila', 'Valenzuela', 'Polo', 'NCR'),

-- Cebu
('Cebu', 'Cebu City', 'Adlaon', 'VII'),
('Cebu', 'Cebu City', 'Agsungot', 'VII'),
('Cebu', 'Cebu City', 'Apas', 'VII'),
('Cebu', 'Cebu City', 'Babag', 'VII'),
('Cebu', 'Cebu City', 'Bacayan', 'VII'),
('Cebu', 'Cebu City', 'Banilad', 'VII'),
('Cebu', 'Cebu City', 'Binaliw', 'VII'),
('Cebu', 'Cebu City', 'Budlaan', 'VII'),
('Cebu', 'Cebu City', 'Busay', 'VII'),
('Cebu', 'Cebu City', 'Calamba', 'VII'),
('Cebu', 'Cebu City', 'Capitol Site', 'VII'),
('Cebu', 'Cebu City', 'Carreta', 'VII'),
('Cebu', 'Cebu City', 'Cogon', 'VII'),
('Cebu', 'Mandaue', 'Alang-alang', 'VII'),
('Cebu', 'Mandaue', 'Bakilid', 'VII'),
('Cebu', 'Mandaue', 'Banilad', 'VII'),
('Cebu', 'Mandaue', 'Casuntingan', 'VII'),
('Cebu', 'Mandaue', 'Cubacub', 'VII'),
('Cebu', 'Lapu-Lapu', 'Agus', 'VII'),
('Cebu', 'Lapu-Lapu', 'Bankal', 'VII'),
('Cebu', 'Lapu-Lapu', 'Caubayan', 'VII'),
('Cebu', 'Lapu-Lapu', 'Caw-oy', 'VII'),
('Cebu', 'Lapu-Lapu', 'Ibo', 'VII'),
('Cebu', 'Talisay', 'Biasong', 'VII'),
('Cebu', 'Talisay', 'Bulacao', 'VII'),
('Cebu', 'Talisay', 'Cansaga', 'VII'),
('Cebu', 'Talisay', 'Lawaan', 'VII'),
('Cebu', 'Talisay', 'Pooc', 'VII'),

-- Davao del Sur
('Davao del Sur', 'Davao City', 'Agdao', 'XI'),
('Davao del Sur', 'Davao City', 'Bago Oshiro', 'XI'),
('Davao del Sur', 'Davao City', 'Buhangin', 'XI'),
('Davao del Sur', 'Davao City', 'Bunawan', 'XI'),
('Davao del Sur', 'Davao City', 'Catalunan Grande', 'XI'),
('Davao del Sur', 'Davao City', 'Catalunan Pequeño', 'XI'),
('Davao del Sur', 'Davao City', 'Cawa-Cawa', 'XI'),
('Davao del Sur', 'Davao City', 'Daliao', 'XI'),
('Davao del Sur', 'Davao City', 'Talomo', 'XI'),
('Davao del Sur', 'Davao City', 'Tugbok', 'XI'),
('Davao del Sur', 'Davao City', 'Toril', 'XI'),
('Davao del Sur', 'Davao City', 'Poblacion', 'XI'),
('Davao del Sur', 'Davao City', 'Bucana', 'XI'),
('Davao del Sur', 'Davao City', 'Lanang', 'XI'),
('Davao del Sur', 'Davao City', 'Sasa', 'XI'),
('Davao del Sur', 'Digos', 'Alegria', 'XI'),
('Davao del Sur', 'Digos', 'Cogon', 'XI'),
('Davao del Sur', 'Digos', 'Digos', 'XI'),
('Davao del Sur', 'Digos', 'Kapatagan', 'XI'),
('Davao del Sur', 'Digos', 'Lungag', 'XI'),

-- Cavite
('Cavite', 'Bacoor', 'Aniban', 'IV-A'),
('Cavite', 'Bacoor', 'Banalo', 'IV-A'),
('Cavite', 'Bacoor', 'Bayanan', 'IV-A'),
('Cavite', 'Bacoor', 'Cabuco', 'IV-A'),
('Cavite', 'Bacoor', 'Casimiro', 'IV-A'),
('Cavite', 'Bacoor', 'Dulong Bayan', 'IV-A'),
('Cavite', 'Bacoor', 'Habay', 'IV-A'),
('Cavite', 'Bacoor', 'Kaingin', 'IV-A'),
('Cavite', 'Bacoor', 'Mababa', 'IV-A'),
('Cavite', 'Bacoor', 'Molino', 'IV-A'),
('Cavite', 'Bacoor', 'Niog', 'IV-A'),
('Cavite', 'Bacoor', 'Poblacion', 'IV-A'),
('Cavite', 'Bacoor', 'Real', 'IV-A'),
('Cavite', 'Bacoor', 'San Nicolas', 'IV-A'),
('Cavite', 'Bacoor', 'Sineguelasan', 'IV-A'),
('Cavite', 'Bacoor', 'Tabing Dagat', 'IV-A'),
('Cavite', 'Bacoor', 'Talon', 'IV-A'),
('Cavite', 'Bacoor', 'Tirona', 'IV-A'),
('Cavite', 'Bacoor', 'Zapote', 'IV-A'),
('Cavite', 'Cavite City', 'Bacoor', 'IV-A'),
('Cavite', 'Cavite City', 'Caridad', 'IV-A'),
('Cavite', 'Cavite City', 'Dalahican', 'IV-A'),
('Cavite', 'Cavite City', 'Lawa', 'IV-A'),
('Cavite', 'Cavite City', 'San Roque', 'IV-A'),
('Cavite', 'Dasmariñas', 'Bucandala', 'IV-A'),
('Cavite', 'Dasmariñas', 'Burol', 'IV-A'),
('Cavite', 'Dasmariñas', 'Dasmariñas', 'IV-A'),
('Cavite', 'Dasmariñas', 'Langkaan', 'IV-A'),
('Cavite', 'Dasmariñas', 'Paliparan', 'IV-A'),
('Cavite', 'Dasmariñas', 'Salawag', 'IV-A'),
('Cavite', 'Dasmariñas', 'San Agustin', 'IV-A'),
('Cavite', 'Imus', 'Alapan', 'IV-A'),
('Cavite', 'Imus', 'Buhay na Tubig', 'IV-A'),
('Cavite', 'Imus', 'Imus', 'IV-A'),
('Cavite', 'Imus', 'Malagasang', 'IV-A'),
('Cavite', 'Imus', 'Poblacion', 'IV-A'),
('Cavite', 'Tagaytay', 'Asisan', 'IV-A'),
('Cavite', 'Tagaytay', 'Calabuso', 'IV-A'),
('Cavite', 'Tagaytay', 'Kaybagyo', 'IV-A'),
('Cavite', 'Tagaytay', 'Maitim', 'IV-A'),
('Cavite', 'Tagaytay', 'Tagaytay', 'IV-A'),
('Cavite', 'Trece Martires', 'Cabezas', 'IV-A'),
('Cavite', 'Trece Martires', 'Conchu', 'IV-A'),
('Cavite', 'Trece Martires', 'Lallana', 'IV-A'),
('Cavite', 'Trece Martires', 'Trece Martires', 'IV-A'),
('Cavite', 'General Trias', 'Biclatan', 'IV-A'),
('Cavite', 'General Trias', 'Gov. Ferrer', 'IV-A'),
('Cavite', 'General Trias', 'Manggahan', 'IV-A'),
('Cavite', 'General Trias', 'Santiago', 'IV-A'),
('Cavite', 'Tanza', 'Amaya', 'IV-A'),
('Cavite', 'Tanza', 'Bigaa', 'IV-A'),
('Cavite', 'Tanza', 'Capantayan', 'IV-A'),
('Cavite', 'Tanza', 'Tanza', 'IV-A'),

-- Add more provinces as needed
('Bulacan', 'Malolos', 'Barasoain', 'III'),
('Bulacan', 'Malolos', 'Babatnin', 'III'),
('Bulacan', 'Malolos', 'Mabini', 'III'),
('Bulacan', 'Malolos', 'Malolos', 'III'),
('Bulacan', 'Marilao', 'Loma de Gato', 'III'),
('Bulacan', 'Marilao', 'Poblacion', 'III'),
('Bulacan', 'Marilao', 'Patubig', 'III'),
('Bulacan', 'Marilao', 'Saingan', 'III'),
('Pampanga', 'Angeles City', 'Angeles', 'III'),
('Pampanga', 'Angeles City', 'Balibago', 'III'),
('Pampanga', 'Angeles City', 'Cutud', 'III'),
('Pampanga', 'San Fernando', 'San Fernando', 'III'),
('Pampanga', 'San Fernando', 'Del Pilar', 'III'),
('Pampanga', 'San Fernando', 'Lourdes', 'III'),
('Laguna', 'Calamba', 'Barangay 1', 'IV-A'),
('Laguna', 'Calamba', 'Barangay 2', 'IV-A'),
('Laguna', 'Calamba', 'Barangay 3', 'IV-A'),
('Laguna', 'Calamba', 'Calamba', 'IV-A'),
('Laguna', 'Santa Rosa', 'Balibago', 'IV-A'),
('Laguna', 'Santa Rosa', 'Caingin', 'IV-A'),
('Laguna', 'Santa Rosa', 'Dita', 'IV-A'),
('Laguna', 'Santa Rosa', 'Santa Rosa', 'IV-A');
